// Per-sport config. Most of a config is derived from the offering tree (rootId, label, participant
// filename); only the tuning that can't be — SPORT_OVERRIDES below — is hand-maintained. Drives
// build-scope-index, scope-catalog, and ground-scope.
// slug names the sport's catalogData/<slug>-scope-index.json file and the index's "sport" field.
// label is what the extractor emits (uppercase free-text in plan.sport).

import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

// Catalog file layout. Durable, tracked artifacts live flat in catalogData/ as
// <slug>-scope-index.json (+ optional curated <slug>-scope-aliases.json). Every build
// intermediate (the shared groups.json tree + per-sport participant feeds) is scratch in
// .catalog-build/ (gitignored), regenerated by scripts/build-catalogs.ts.
const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
export const CATALOG_DIR = join(ROOT, "catalogData");
export const BUILD_DIR = join(ROOT, ".catalog-build");
export const GROUPS_PATH = join(BUILD_DIR, "groups.json"); // shared tree, kept between runs
export const slugify = (name: string): string =>
  name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
export const scopeIndexPath = (slug: string): string => join(CATALOG_DIR, `${slug}-scope-index.json`);
export const scopeAliasPath = (slug: string): string => join(CATALOG_DIR, `${slug}-scope-aliases.json`);

export type SportConfig = {
  slug: string;
  label: string;
  sportRootId: number;
  participantsFile: string;
  individual?: boolean;
  // Pass --national-teams to the normalizer (flag NT clubs / link countryTeamId). Basketball is off until
  // FIBA competitions appear in the offering (see project notes); flip to true when they do.
  nationalTeams?: boolean;
  // Individual sports only: maps a sport-root child (tour) NAME to the feed CODE that build-scope-index
  // reads for gender de-pollution. fetch-participants writes one <code>_participants.json per entry.
  tourFeeds?: Record<string, string>;
};

// Per-sport tuning that CANNOT be read from the offering tree: individual-sport ingest,
// national-team detection, and the tour->feed map for gender de-pollution. Keyed by slug.
// A sport with no entry builds as a plain team sport, NT off — correct for the majority.
// Doubles / NT-variant support for more sports plugs in here (see project notes).
const SPORT_OVERRIDES: Record<string, Pick<SportConfig, "individual" | "nationalTeams" | "tourFeeds">> = {
  football: { nationalTeams: true },
  tennis: {
    individual: true, nationalTeams: true,
    tourFeeds: { "ATP": "ATP", "WTA": "WTA", "ITF Men": "ITFM", "ITF Women": "ITFW", "UTR Pro Tennis Series": "UTRM", "UTR Pro Tennis Series Women": "UTRW" },
  },
  // Individual sports: competitors are top-level PARTICIPANT entries, not team rosters. Marked
  // individual so they build via the individual path (players captured, not dropped). Fuller
  // doubles / NT-variant handling (Ryder Cup, Davis-Cup-style, etc.) is deferred — see project notes.
  golf: { individual: true },
  darts: { individual: true },
  snooker: { individual: true },
  chess: { individual: true },
  boxing: { individual: true },
  cycling: { individual: true },
  motorsports: { individual: true },
  "formula-1": { individual: true },
  "ufc-mma": { individual: true },
  "table-tennis": { individual: true },
  padel: { individual: true },
  "winter-sports": { individual: true },
  "horse-racing": { individual: true },
  greyhounds: { individual: true },
  trotting: { individual: true },
};

type TreeNode = { id: number; name: string; groups?: TreeNode[] };
let topLevelCache: TreeNode[] | undefined; // memoized parse of GROUPS_PATH (build time); absent at runtime
function topLevelSports(): TreeNode[] {
  if (topLevelCache) return topLevelCache;
  try {
    const raw = JSON.parse(readFileSync(GROUPS_PATH, "utf8")) as { group?: TreeNode } & TreeNode;
    topLevelCache = (raw.group ?? raw).groups ?? [];
    return topLevelCache;
  } catch {
    return []; // no tree yet (runtime, or before fetch-groups) — not cached, so a later read retries
  }
}

// Full build config for a tree sport node: rootId + label + participant filename come from the node,
// the flags from SPORT_OVERRIDES.
export function sportConfigFromNode(node: { id: number; name: string }): SportConfig {
  const slug = slugify(node.name);
  return { slug, label: node.name.toUpperCase(), sportRootId: node.id, participantsFile: `${slug}_participants.json`, ...SPORT_OVERRIDES[slug] };
}

// Every top-level sport in the offering tree, as build configs. Drives scripts/build-catalogs.ts.
export function allSportConfigs(): SportConfig[] {
  return topLevelSports().map(sportConfigFromNode);
}

// Resolve a sport by name/slug. KNOWN when it's a top-level node in the offering tree (build time,
// GROUPS_PATH present) OR its catalog was already built (runtime: catalogData/<slug>-scope-index.json).
// undefined otherwise — resolve.ts uses that as the "we don't support this sport yet" gate. sportRootId
// is 0 in the runtime (catalog-only) path since nothing downstream reads it there.
export function getSport(sport: string): SportConfig | undefined {
  const slug = slugify(sport);
  const node = topLevelSports().find((n) => slugify(n.name) === slug);
  if (node) return sportConfigFromNode(node);
  if (existsSync(scopeIndexPath(slug))) {
    return { slug, label: slug.toUpperCase(), sportRootId: 0, participantsFile: `${slug}_participants.json`, ...SPORT_OVERRIDES[slug] };
  }
  return undefined;
}
